name: Prepare Flutter Repository
description: 'Prepares the Flutter repository by running code generation and localization tasks.'
inputs:
  run-build-runner:
    description: 'Whether to run build_runner for code generation. Automatically discovers and runs build_runner for all Flutter packages in the repository.'
    required: false
    default: 'true'
  run-gen-l10n:
    description: 'Whether to run gen-l10n for localization code generation. Automatically discovers and runs gen-l10n for all Flutter packages in the repository.'
    required: false
    default: 'true'
  gen-l10n-fails-if-untranslated:
    description: 'Whether to fail the gen-l10n step if untranslated strings are found. This will check for the presence of an untranslated-messages-file in the l10n configuration and fail if any untranslated messages are found.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Run Build Runner
      if: ${{ inputs.run-build-runner == 'true' }}  
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/build_runner/build_runner.sh
        $GITHUB_ACTION_PATH/build_runner/build_runner.sh

    - name: Run gen-l10n
      if: ${{ inputs.run-gen-l10n == 'true' }}
      env:
        FAILS_IF_UNTRANSLATED: ${{ inputs.gen-l10n-fails-if-untranslated }}
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/gen-l10n/gen-l10n.sh
        $GITHUB_ACTION_PATH/gen-l10n/gen-l10n.sh
      
      
