name: Check Flutter project
description: 'Runs a series of checks on the Flutter project, including static analysis, license compatibility, unit tests and widget tests.'
inputs:
  # Analyze options
  run-analyze:
    description: 'Whether to run flutter analyze. If false, the analyze step will be skipped.'
    required: false
    default: 'true'
  analyze-fails-if-infos:
    description: 'Whether to fail the analyze step if info level issues are found.'
    required: false
    default: 'true'
  analyze-fails-if-warnings:
    description: 'Whether to fail the analyze step if warning level issues are found.'
    required: false
    default: 'true'

  # License check options
  run-license:
    description: 'Whether to run license check. If false, the license check step will be skipped.'
    required: false
    default: 'false'
  compatible-licenses-conf-path:
    description: 'Path to a file containing a list of compatible licenses for the license check step.'
    required: false

  # Test options
  run-test:
    description: 'Whether to run flutter test. If false, the test step will be skipped.'
    required: false
    default: 'true'
  dart-define:
    description: 'Additional key-value pairs that will be available as constants from the String.fromEnvironment, bool.fromEnvironment, and int.fromEnvironment constructors.'
    required: false
    default: ''
  dart-define-from-file:
    description: 'The path of a .json or .env file containing key-value pairs that will be available as environment variables. These can be accessed using the String.fromEnvironment, bool.fromEnvironment, and int.fromEnvironment constructors.'
    required: false
    default: ''
  flavor:
    description: 'The app flavor to use when running tests. This should match the flavor defined in your platform-specific build setup (e.g., product flavors in Android Gradle scripts or custom Xcode schemes).'
    required: false
    default: ''
  concurrency:
    description: 'The number of concurrent test processes to run. This will be ignored when running integration tests.'
    required: false
    default: '1'
  timeout:
    description: 'The default timeout for individual tests, specified either in seconds (e.g. "60s"), as a multiplier of the default test timeout (e.g. "2x"), or as the string "none" to disable test timeouts entirely. This value does not apply to the default test suite loading timeout.'
    required: false
    default: '60s'
  ignore-timeouts:
    description: 'Ignore all timeouts. Useful when testing a big application that requires a longer time to compile (e.g. running integration tests for a Flutter app).'
    required: false
    default: 'false'
  run-coverage:
    description: 'Run tests with coverage. Even if false, coverage will be generated if deploy-report is set to github-pages or artifact.'
    required: false
    default: 'false'
  create-coverage-badge:
    description: 'Whether to create a coverage badge based on the generated coverage report. The badge will be created in the root of the repository with the name "coverage_badge.svg".'
    required: false
    default: 'false'
  coverage-badge-output-path:
    description: 'The path where the coverage badge will be created. This input is only used if create-coverage-badge is set to true. The default value is "coverage/html" in the root of the repository.'
    required: false
    default: 'coverage/html'
  no-pub:
    description: 'Whether to skip running pub get before running tests. Set to true if you have already run pub get in a previous step or if you are using a custom pub cache.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run Analyze
      if: ${{ inputs.run-analyze == 'true' }}
      env:
        ANALYZE_FAILS_IF_INFOS: ${{ inputs.analyze-fails-if-infos }}
        ANALYZE_FAILS_IF_WARNINGS: ${{ inputs.analyze-fails-if-warnings }}
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/analyze/analyze.sh
        $GITHUB_ACTION_PATH/analyze/analyze.sh
      
    - name: Check Licenses
      if: ${{ inputs.run-license == 'true' }}
      env:
        COMPATIBLE_LICENSES_CONF_PATH: ${{ inputs.compatible-licenses-conf-path }}
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/license/license.sh
        $GITHUB_ACTION_PATH/license/license.sh
    
    - name: Run Tests
      if: ${{ inputs.run-test == 'true' }}
      env:
        DART_DEFINE: ${{ inputs.dart-define }}
        DART_DEFINE_FROM_FILE: ${{ inputs.dart-define-from-file }}
        FLAVOR: ${{ inputs.flavor }}
        CONCURRENCY: ${{ inputs.concurrency }}
        TIMEOUT: ${{ inputs.timeout }}
        IGNORE_TIMEOUTS: ${{ inputs.ignore-timeouts }}
        RUN_COVERAGE: ${{ inputs.run-coverage }}
        CREATE_COVERAGE_BADGE: ${{ inputs.create-coverage-badge }}
        NO_PUB: ${{ inputs.no-pub }}
        COVERAGE_BADGE_OUTPUT_PATH: ${{ inputs.coverage-badge-output-path }}
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/test/test.sh
        $GITHUB_ACTION_PATH/test/test.sh
     
