name: Publish to Firebase App Distribution
description: Publish the app to Firebase App Distribution
inputs:
  firebase-release-binary-file:
    description: 'File you want to upload'
    required: true
  firebase-service-account-base64:
    description: 'Base64 encoded Firebase service account JSON key file'
    required: true
  firebase-app-id:
    description: 'Firebase App ID (e.g. 1:1234567890:android:abcdef123456)'
    required: true
  firebase-groups:
    description: 'Comma-separated list of tester groups to distribute the app to (optional)'
    required: false
  firebase-groups-file:
    description: 'Path to a file containing a comma-separated list of tester groups to distribute the app to (optional)'
    required: false
  firebase-testers:
    description: 'Comma-separated list of tester email addresses to distribute the app to (optional)'
    required: false
  firebase-testers-file:
    description: 'Path to a file containing a comma-separated list of tester email addresses to distribute the app to (optional)'
    required: false
  firebase-release-notes:
    description: 'Release notes for this distribution (optional)'
    required: false
  firebase-release-notes-file:
    description: 'Path to a file containing release notes for this distribution (optional)'
    required: false
  firebase-debug:
    description: 'Whether to enable debug logging for the upload process (default: false)'
    required: false
    default: 'false'
  firebase-test-devices:
    description: 'Comma-separated list of test device IDs to distribute the app to (optional, only for iOS)'
    required: false
  firebase-test-devices-file:
    description: 'Path to a file containing a comma-separated list of test device IDs to distribute the app to (optional, only for iOS)'
    required: false
  firebase-test-username:
    description: 'Username for authenticating with the Firebase CLI (optional)'
    required: false
  firebase-test-username-file:
    description: 'Path to a file containing the username for authenticating with the Firebase CLI (optional)'
    required: false
  firebase-test-password:
    description: 'Password for authenticating with the Firebase CLI (optional)'
    required: false
  firebase-test-password-file:
    description: 'Path to a file containing the password for authenticating with the Firebase CLI (optional)'
    required: false
  firebase-test-non-blocking:
    description: 'Whether to run the upload process in non-blocking mode (default: false)'
    required: false
    default: 'false'
  firebase-test-case-ids:
    description: 'Comma-separated list of test case IDs to associate with this distribution (optional)'
    required: false
  firebase-test-case-ids-file:
    description: 'Path to a file containing a comma-separated list of test case IDs to associate with this distribution (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Add permissions
      run: chmod +x $GITHUB_ACTION_PATH/firebase-app-distribution.sh
      shell: bash

    - name: Publish to Firebase App Distribution
      env:
        FIREBASE_RELEASE_BINARY_FILE: ${{ inputs.firebase-release-binary-file }}
        FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ inputs.firebase-service-account-base64 }}
        FIREBASE_APP_ID: ${{ inputs.firebase-app-id }}
        FIREBASE_GROUPS: ${{ inputs.firebase-groups }}
        FIREBASE_GROUPS_FILE: ${{ inputs.firebase-groups-file }}
        FIREBASE_TESTERS: ${{ inputs.firebase-testers }}
        FIREBASE_TESTERS_FILE: ${{ inputs.firebase-testers-file }}
        FIREBASE_RELEASE_NOTES: ${{ inputs.firebase-release-notes }}
        FIREBASE_RELEASE_NOTES_FILE: ${{ inputs.firebase-release-notes-file }}
        FIREBASE_DEBUG: ${{ inputs.firebase-debug }}
        FIREBASE_TEST_DEVICES: ${{ inputs.firebase-test-devices }}
        FIREBASE_TEST_DEVICES_FILE: ${{ inputs.firebase-test-devices-file }}
        FIREBASE_TEST_USERNAME: ${{ inputs.firebase-test-username }}
        FIREBASE_TEST_USERNAME_FILE: ${{ inputs.firebase-test-username-file }}
        FIREBASE_TEST_PASSWORD: ${{ inputs.firebase-test-password }}
        FIREBASE_TEST_PASSWORD_FILE: ${{ inputs.firebase-test-password-file }}
        FIREBASE_TEST_NON_BLOCKING: ${{ inputs.firebase-test-non-blocking }}
        FIREBASE_TEST_CASE_IDS: ${{ inputs.firebase-test-case-ids }}
        FIREBASE_TEST_CASE_IDS_FILE: ${{ inputs.firebase-test-case-ids-file }}
      run: $GITHUB_ACTION_PATH/firebase-app-distribution.sh
      shell: bash
