name: Code Generation with Build Runner
description: 'Automatically discovers and runs code generation using build_runner for all Flutter packages in the repository.'

runs:
  using: 'composite'
  steps:
    - name: Run Build Runner
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/build_runner.sh
        $GITHUB_ACTION_PATH/build_runner.sh
      
