name: Publish Flutter iOS app to App Store
description: |
  Publish the built Flutter iOS app to the App Store using the
  App Store Connect API. This action assumes that you have already
  built the iOS app and generated an .ipa file in a previous step.

inputs:
  apple-api-key-id:
    description: 'Apple API key ID. Required for publishing to App Store Connect.'
    required: true
  apple-api-key-issuer-id:
    description: 'Apple API key issuer ID. Required for publishing to App Store Connect.'
    required: true
  apple-api-key-content:
    description: 'Apple API key content (.p8 file, base64 encoded). Required for publishing to App Store Connect.'
    required: true
  ios-app-path:
    description: 'Path to the iOS .ipa file'
    required: false
    default: 'build/ios/ipa/*.ipa'

runs:
  using: 'composite'
  steps:
    - name: Publish to App Store Connect
      shell: bash
      env:
        API_KEY_ID: ${{ inputs.apple-api-key-id }}
        API_ISSUER_ID: ${{ inputs.apple-api-key-issuer-id }}
        API_KEY_CONTENT: ${{ inputs.apple-api-key-content }}
        APP_PATH: ${{ inputs.ios-app-path }}
      run: |
        # Create private key file
        mkdir -p ~/.appstoreconnect/private_keys
        echo "$API_KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_$API_KEY_ID.p8

        # Upload
        xcrun altool --upload-app --type ios --file "$APP_PATH" --apiKey "$API_KEY_ID" --apiIssuer "$API_ISSUER_ID"
