name: Publish to Firebase Hosting
description: Publish the built web app to Firebase Hosting
inputs:
  firebase-service-account-base64:
    description: 'Base64 encoded Firebase service account key (JSON file)'
    required: true
  firebase-project-id:
    description: 'Firebase project ID to publish to'
    required: false
  firebase-target:
    description: 'Firebase Hosting target to deploy to (optional)'
    required: false
  firebase-debug:
    description: 'Whether to enable debug logging for the deployment process (default: false)'
    required: false
    default: 'false'
  firebase-message:
    description: 'A message to include with the deployment (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Add permissions
      run: chmod +x $GITHUB_ACTION_PATH/firebase-hosting.sh
      shell: bash

    - name: Publish to Firebase Hosting
      env:
        FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ inputs.firebase-service-account-base64 }}
        FIREBASE_PROJECT_ID: ${{ inputs.firebase-project-id }}
        FIREBASE_TARGET: ${{ inputs.firebase-target }}
        FIREBASE_DEBUG: ${{ inputs.firebase-debug }}
        FIREBASE_MESSAGE: ${{ inputs.firebase-message }}
      run: $GITHUB_ACTION_PATH/firebase-hosting.sh
      shell: bash
