name: Publish Flutter app to Snap Store
description: Publish the built Flutter app to the Snap Store

inputs:
  snap-store-token:
    description: 'Snap Store API token with permissions to publish snaps'
    required: true

runs:
  using: composite
  steps:
    - name: Setup LXD (for managed builds)
      uses: canonical/setup-lxd@v0.1.2

    - name: Publish to Snap Store
      shell: bash
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.snap-store-token }}
      run: |
        chmod +x ${{ github.action_path }}/snap-store.sh
        bash ${{ github.action_path }}/snap-store.sh
